language: java
sudo: false

## We should try to support the main LTS (long-term-support) releases
jdk:
  - openjdk8
  - openjdk11

# As the build will download JAR files from Maven Central, optimize their storage,
# so they do not get re-downloaded each time
cache:
  directories:
  - .autoconf
  - $HOME/.m2

notifications:
  email: true

services:
  - docker


script: travis_wait 50 mvn clean verify --fae

# After build is finished, upload coverage results to CodeCov
after_success:
  - bash <(curl -s https://codecov.io/bash)